name: Publish
on:
  workflow_run:
    workflows: [Release2]
    types:
      - completed

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release: true

  release:
    needs: build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Finished
        run: echo "FINISHED"
